services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  rooms:
    build:
      context: ./
      dockerfile: ./rooms/Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}

  users:
    build:
      context: ./
      dockerfile: ./users/Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
