services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq

  rooms:
    build:
      context: ./
      dockerfile: ./rooms/Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      RABBIT_HOST: rabbitmq

  notifications:
    build:
      context: ./
      dockerfile: ./notifications/Dockerfile
    environment:
      RABBIT_HOST: rabbitmq
    ports:
        - 3001:3000

  users:
    build:
      context: ./
      dockerfile: ./users/Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}

  api:
    build:
      context: ./
      dockerfile: ./api/Dockerfile
    environment:
      USERS_HOST: users
      ROOMS_HOST: rooms
    ports:
      - 3000:3000
